### ISSUE TITLE
Add "national" key on the standings response

### ISSUE THREAD

**Issue by Scrzz** [api-sports/public-roadmap#124]
Add the "national" boolean if the team is a national team when fetching the standings.

```
var options = {
  method: 'GET',
  url: 'https://api-football-v1.p.rapidapi.com/v3/standings',
  params: {season: '2020', league: '39'},
  headers: {
    'x-rapidapi-host': 'api-football-v1.p.rapidapi.com',
    'x-rapidapi-key': '***********'
  }
};
```

**Comment by api-sports** [comment]
Hi,

This information is already contained in the endpoint "teams" so it is not necessary to report it in the endpoint "standings" knowing that depending on the competition you can know if it is an international competition or not.

I took the liberty to remove your API-KEY from your POST in order to avoid that someone else uses it instead of you

Best
