### ISSUE TITLE
Missing team & player statistics for german league "Regionalliga Bayern"

### ISSUE THREAD

**Issue by radtki** [api-sports/public-roadmap#18]
Unfortunately, there are no team and player statistics for this league available yet.

**Comment by api-sports** [comment]
Hi,

This is not a new feature but of data that we don't have yet about this competition. 

All the data we have is available in the API.

Best

**Comment by radtki** [comment]
Would be nice, if you can publish a an bugfix-repo too. I'm missing an overview about known and new bugs and an related timeline for it. Is it also in planning?

**Comment by api-sports** [comment]
Hi,

We have one, but it is private, all the "bugs" reported by users are put in front and followed by our developers.

We prefer not to make it public for the moment because we filter all the requests directly from the chat to avoid having bugs reported that are not related to the API itself.

Best
