### ISSUE TITLE
Wrong Total Passes or Ball Posession in the fixture endpoint

### ISSUE THREAD

**Issue by Scrzz** [api-sports/public-roadmap#83]
When you calculate the Total Passes percentage the result is the same with the Ball Possesion percentage.

Take this endpoint for example ****fixtures/statistics?fixture=723370

- Ball posession 66% vs 34%
- Total Passes 823 vs 424 which is 66% vs 34%

You can take any fixture and you will receive the same percentage between Ball Possesion and Total Passes. Please check.

Thank you!

**Comment by thenashone** [comment]
hey @Scrzz. mind sharing the furmula you used to worked it out?  as i get 51% 

(100 / 823) * 424.

**Comment by thenashone** [comment]
hi @Scrzz mind explaning to me what you mean as im about to start working with the match statistics on my project.

Using your example i cant see what you mean.
Italy had 66% posession
England had 34% possession

Italy had 823 passes and completed 729 (88.2%) (api retruns 89%)
England had 424 passes and completed 319 (75.2%) (api retruns 75%)



Italy had 51% more passes than england (399 more)

**Comment by api-sports** [comment]
Hi,

This section does not take into account Bugs but only requests for new features for APIs.

Please contact the support via the dashboard, if you have questions about the data or to report bugs.

Thanks

**Comment by Scrzz** [comment]
Hi @thenashone .

Italy has 823 passes and England has 424. This means 1247 passes in total. So if you calculate the percentage of Italy passes you will get 66% from the total.

TeamAPasses * 100 / (TeamAPasses + TeamBPasses)
824 * 100 / 1247 = 66% for Italy

If the API gets the total passes and they calculate the passes for each team taking in consideration the ball possession, then the total passes value are not so reliable.

**Comment by thenashone** [comment]
@Scrzz ty that makes sence thought i was going crazy.

**Comment by api-sports** [comment]
Hi,

Just for info we use the **Automatic calculation**

**Manual clock**
For mid-level soccer games, possession is often calculated using a hand clock. During the game, the individual in charge of the game clock will also have a chess-type clock in front of him with two dials and a button above each dial. Once he sees the ball change possession, he will press the button above the dial of the corresponding team. He will hit between each dial on each change of possession. Although this calculation keeps a fairly accurate time of possession, it is subject to human error, which is why it is not often used in professional games.


**Automatic calculation**
In high-level soccer matches, time of possession is calculated using an automated calculation that is based directly on the number of passes each team completes during a game. Each pass is calculated and inserted directly into this equation. The total number of passes is then divided by the total number of passes in the game to get a percentage of the total. While this is not directly a time calculation, it does end up being directly correlated to a team's time of possession during a game.

**Change of Possession**
A change of possession occurs in a soccer game when the ball is stolen by an opponent or when the ball goes out of play, giving the ball to the other opponent. A change of possession is always carried out according to the official rules of the game. Despite this, referees who enforce the game are subject to human error, resulting in missed calls and change of possession calls when they should not have occurred.

**Comment by Scrzz** [comment]
@api-sports Thank you for the info.
